# AWS Configuration for shared infrastructure
# This file contains sensitive configuration and should not be committed to git

# Basic configuration
project_name: "hogtown"
aws_profile: "hogtown"
aws_region: "us-east-1"

# GitHub repository URL for App Runner source connection
github_repository_url: "https://github.com/pvnick/hogtown"

# VPC Configuration
vpc_cidr: "10.0.0.0/16"
availability_zones: []

# Database configuration
postgres_version: "17.2"
db_instance_class: "db.t4g.micro"
db_allocated_storage: 20
db_max_allocated_storage: 1000
multi_az: false
backup_retention_period: 7
monitoring_interval: 0
performance_insights_enabled: false
deletion_protection: true
skip_final_snapshot: false

# Application secrets (optional - leave blank to use defaults)
prosopo_site_key: "5EcHAuJuWAevsRezYfkXUtFQ1LE4iTk9sZkkeTynrf97W6Xf"
prosopo_secret_key: "panther flavor blue negative verb horse note cave mirror deny omit obscure"
default_from_email: "noreply@hogtowncatholic.org"
allowed_hosts: ""