# Staging environment configuration

# Basic configuration
project_name: "hogtown"
aws_profile: "hogtown"
aws_region: "us-east-1"

# Backend configuration - must match your S3 bucket for shared state
shared_state_bucket: "hogtown-63835-terraform-state-shared"
shared_state_key: "hogtown/shared.tfstate"
shared_state_region: "us-east-1"

# Environment-specific configuration
staging_branch: "develop"
auto_deploy_enabled: true
staging_cpu: "0.25 vCPU"
staging_memory: "0.5 GB"
observability_enabled: false
log_retention_days: 7

# Health check configuration
health_check_path: "/health/"
health_check_healthy_threshold: 1
health_check_unhealthy_threshold: 3
health_check_interval: 10
health_check_timeout: 5