# Generated by Django 5.2.2 on 2025-06-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_requested_ministry_details_alter_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="approval_email_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether approval notification email was sent successfully",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_failure_reason",
            field=models.TextField(
                blank=True, help_text="Last email sending failure reason"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="rejection_email_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether rejection notification email was sent successfully",
            ),
        ),
    ]
