name: Deploy dev to production

on:
  workflow_dispatch:

jobs:
  execute-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: hogtown-dev.paulnickerson.dev
        username: bitnami
        key: ${{ secrets.DEV_SERVER_SSH_KEY }}
        script: |
          echo "Dumping database tables"
          /bitnami/wordpress/wp-content/migration/dump_db.sh
