name: Build and Push to ECR

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials for ECR
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.ECR_PUSH_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ECR_PUSH_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/hogtown-app:${{ github.sha }}
          ${{ steps.login-ecr.outputs.registry }}/hogtown-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Force App Runner deployment
      if: github.ref == 'refs/heads/main'
      run: |
        SERVICE_ARN=$(aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='hogtown-app'].ServiceArn" --output text)
        if [ ! -z "$SERVICE_ARN" ]; then
          echo "Triggering deployment for service: $SERVICE_ARN"
          aws apprunner start-deployment --service-arn $SERVICE_ARN
        fi