name: Dump dev website and push to git

on:
  workflow_dispatch:

jobs:
  execute-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ssh.dev.hogtowncatholic.org
        username: bitnami
        key: ${{ secrets.DEV_SERVER_SSH_KEY }}
        script: |
          echo "Install needed utils"
          sudo apt-get install -y rsync git
          
          echo "Configuring git credentials"
          USERID="pvnick"
          PAT="${{ secrets.REPO_PAT }}"
          git config --global credential.helper store
          echo "https://${USERID}:${PAT}@github.com" > ~/.git-credentials

          echo "Resetting the hogtown repo"
          cd /home/bitnami/
          rm -rf hogtown
          git clone https://github.com/pvnick/hogtown.git
          cd hogtown
        
          echo "Dumping site"
          ./dump.sh

          echo "Pushing changes to git"
          git config --global user.name 'Hogtown CI'
          git config --global user.email 'ci@hogtowncatholic.org'
          git add .
          git commit -m "Uploading migration data [skip ci]"
          git pull --no-edit
          git push
