name: Promote repo to prod

on:
  workflow_dispatch:

jobs:
  execute-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ssh.hogtowncatholic.org
        username: bitnami
        key: ${{ secrets.PROD_SERVER_SSH_KEY }}
        script: |
          echo "Install needed utils"
          sudo apt-get install -y rsync git

          echo "Configuring git credentials"
          USERID="pvnick"
          PAT="${{ secrets.REPO_PAT }}"
          git config --global credential.helper store
          echo "https://${USERID}:${PAT}@github.com" > ~/.git-credentials

          echo "Resetting the hogtown repo"
          cd /home/bitnami/
          rm -rf hogtown
          git clone https://github.com/pvnick/hogtown.git
          cd hogtown
        
          echo "Promoting site"
          ./promote.sh