name: Promote repo to prod

on:
  workflow_dispatch:

jobs:
  execute-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ssh.hogtowncatholic.org
        username: bitnami
        key: ${{ secrets.PROD_SERVER_SSH_KEY }}
        script: |
          echo hello world